# this file uploaded to Fauna to define the backend logic
type songStats {
  spotifyId: String!
  claps: Int
}

type Query {
  allSongStats: [songStats!]
  songStatsBySpotifyId(spotifyId: String!): songStats!
  topSongStats: [songStats!] @index(name: "topSongStats")
}
